#!/bin/sh

sh Integration/Scripts/swift-format-it.sh

# Make sure Version.xcconfig is up to date
REPO_ROOT=$(git rev-parse --show-toplevel)
for train in mac ios tv; do
    case $train in
        mac|tv) OUTPUT_DIR="${train}os" ;;
             *) OUTPUT_DIR=$train ;;
    esac

    out="${REPO_ROOT}/apps/$OUTPUT_DIR/"
    mint run git-lhc describe --train $train \
        --channel alpha \
        --show head \
        --template Version.xcconfig \
        --output "$out"

    git add "$out/Version.xcconfig"
done

# Force patch version to 99 to better test update/migration code on debug builds
sed -i '' 's/\([0-9][0-9]*\.[0-9][0-9]*\)\.[0-9]*/\1.99/' apps/*/Version.xcconfig

git add apps/*/Version.xcconfig
