stages:
  - prepare
  - i18n
  - github
  - trigger

##
## ---- Variables
##

variables:
  ATLAS_DEPLOY_ENV: "true"
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  # We use this variable when we run publish-github jobs
  RELEASE_GITHUB_REPOSITORY: git@github.com:ProtonVPN/ios-mac-app.git
  # Folder where jobs put their output like build binaries, test results, etc.
  JOBS_OUTPUT_PATH: "output"
  # Default tart settings
  TART_EXECUTOR_ALWAYS_PULL: "false"
  TART_EXECUTOR_HEADLESS: "false"
  DESCRIBE_DIR: "apple-vpn-ci"
  PIPELINE_TEMPLATE: "gitlab-pipeline.yml"
  IMAGES: $IMAGES

default:
  image: "team-vpn-macos-15.5-xcode-16.4"

# Only start a pipeline if it's for a merge request, if the pipeline has been scheduled, if this is a merge result onto
# the develop branch, or if this is a tag which begins with a recognized tag prefix like `mac` or `ios`.
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" ||
          $CI_PIPELINE_SOURCE == "schedule" ||
          $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ||
          $CI_COMMIT_TAG =~ /mac|ios|tv\/\d+/
include:
  # Generate a dynamic pipeline for each build train (platform) we support. This pipeline is based off of the template
  # at Integration/Templates/gitlab-pipeline.yml, and builds, tests, and publishes all necessary artifacts.
  #
  # Jobs that do not require running multiple times for each build train should remain in .gitlab-ci.yml.
  # - component: gitlab.protontech.ch/proton/devops/cicd-components/community/git-lhc/describe (not in the catalog yet)
  - project: 'proton/devops/cicd-components/community/git-lhc'
    file: templates/describe.yml
    ref: 0.9.0-alpha.22
    inputs:
      output_directory: apple-vpn-ci
      cmd_prefix: "mint run "
      templates: "$PIPELINE_TEMPLATE pages.docc fastlane slack-message.txt sparkle-item.xml issue-hashes.txt"
      trains: $TRAINS


    # Will create 2 jobs to translate the 2 projects and trigger
    # a weekly MR with translations inside (1 MR for both)
    # Langauges defined inside the config service
  - component: $CI_SERVER_FQDN/translations/ci/groups@~latest
    inputs:
      stage: i18n
      projects:
        - apple-vpn
        - apple-vpn-tv
      before_script_sources:
        - |
          export SKIP_MACROS_SETUP=true
          export SKIP_MINT_BOOTSTRAP=true

        - unset LC_ALL
        - ./Integration/Scripts/pipeline_setup.sh
        - |
          ./Integration/Scripts/replace_dotenv.sh -e "$NAMES_DOTENV" \
              libraries/Foundations/Strings/Sources/Strings/Strings.swift \
              libraries/Foundations/Strings/Sources/Strings/Resources/en.lproj/* \
              libraries/Foundations/Domain/Sources/Domain/Constants.swift

##
## ---- Job templates shamefully stolen from Integration/Templates/gitlab-pipeline.yml
##

.job_template:
  before_script:
    - Integration/Scripts/pipeline_setup.sh

.mint_cache:
  variables:
    MINT_PATH: $CI_PROJECT_DIR/.caches/mint
    MINT_LINK_PATH: $MINT_PATH/bin
    MINT_CACHE_POLICY: pull-push
  cache: &mint_cache
    - key: mint-xcode-16.2-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - mint-Xcode-16.2-$CI_DEFAULT_BRANCH
      paths:
        - $MINT_PATH
      policy: $MINT_CACHE_POLICY

##
## ---- Linting/pipeline generation
##

# Lint the project, then generate the pipeline.
prepare:
  extends:
    - .job_template
    - .mint_cache
  variables:
    GIT_DEPTH: 200
    GIT_SUBMODULE_DEPTH: 1
    GIT_SUBMODULE_STRATEGY: normal
  stage: prepare
  tags:
    - vpn-apple-xs
  before_script:
    - !reference [.job_template, before_script]
    - !reference [.lhc_describe, before_script]
  script:
    - |
      # Lint commits, code quality, and translations on branches only (not tags)
      if [ -z "$CI_COMMIT_TAG" ] && [ "$CI_MERGE_REQUEST_EVENT_TYPE" != "merge_train" ]; then
          mint run git-lhc lint --verbose --train ios # Lint commit history
          Integration/Scripts/code_quality.sh # Lint code quality
          Integration/Scripts/lint_translations.sh # Lint string files
      fi
    - if [ -n "$CI_COMMIT_TAG" ]; then ./Integration/Scripts/check_tag.sh; fi
    - !reference [.lhc_describe, script] # Generate child pipelines
    - | # Use template output to fetch workflow information, and update the repo (don't require success)
      if [ -n "$CI_MERGE_REQUEST_IID" ]; then
        Integration/Scripts/update_workflow_metadata.sh || true
      elif [ -n "$CI_COMMIT_TAG" ]; then
        Integration/Scripts/update_workflow_metadata.sh "$DESCRIBE_DIR/release/issue-hashes.txt" || true
      fi

      # Don't fail if push doesn't work, there will be plenty of opportunities to update in a later pipeline
      git push origin refs/notes/proton/attrs || true
  rules:
    - if: $CI_MERGE_REQUEST_TITLE =~ /^Draft:/ # Don't run pipelines automatically for draft MRs
      when: manual
    - if: $I18N_SCHEDULES_FILTER == "commit-translations" # Don't run pipelines when syncing from crowdin
      when: never
    - when: always
  cache:
  cache:
    - *mint_cache
    - key: suggest-reviewer-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - suggest-reviewer-$CI_DEFAULT_BRANCH
      paths:
        - $CI_PROJECT_DIR/.caches/review
  artifacts:
    expire_in: 5 days
    paths:
      - apple-vpn-ci/*/*
      - codequality_report.json
    reports:
      codequality: codequality_report.json

##
## ---- Trigger dynamic pipelines
##

# If a tag was pushed, then only one pipeline was created. Otherwise, LHC generated one pipeline for each build train,
# and we need to trigger each one in a matrix.

# Trigger the pipeline generated by the describe job, for one or all trains as necessary.
.trigger_template:
  stage: trigger
  variables:
    # For tagging commits with the pipeline id
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
    # For fetching job artifacts (avoids a bug [!366870] in Gitlab dependencies)
    PARENT_JOB_ID: $CI_JOB_ID
  trigger:
    strategy: depend
    forward:
      pipeline_variables: true
      yaml_variables: true

.trigger_deploy:
  stage: deploy
  strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

trigger:tag:
  extends:
    - .trigger_template
  trigger:
    include:
      - artifact: "$DESCRIBE_DIR/release/$PIPELINE_TEMPLATE"
        job: prepare
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never

trigger:branch:
  extends:
    - .trigger_template
  parallel:
    matrix:
      - TRAIN: [ios, mac, tv]
  trigger:
    include:
      - artifact: "$DESCRIBE_DIR/$TRAIN/$PIPELINE_TEMPLATE"
        job: prepare
  rules:
    - if: $SLI_TEST == "true"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $I18N_SCHEDULES_FILTER == "commit-translations"
      when: never
    - when: on_success

trigger:sli:branch:
  extends:
    - .trigger_template
  parallel:
    matrix:
      - TRAIN: [ios]
  trigger:
    include:
      - artifact: "$DESCRIBE_DIR/$TRAIN/$PIPELINE_TEMPLATE"
        job: prepare
  rules:
    - if: $SLI_TEST == "true"
      when: on_success
    - when: never
