//
//  Created on 23/01/2024.
//
//  Copyright (c) 2024 Proton AG
//
//  ProtonVPN is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  ProtonVPN is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with ProtonVPN.  If not, see <https://www.gnu.org/licenses/>.

import Foundation

import Dependencies
import Sharing

import ProtonCoreFeatureFlags

import CommonNetworking
import Domain
import Telemetry
import VPNAppCore

actor TelemetryLegacyConnectionStatusReporter {
    struct Error: Swift.Error {
        let localizedDescription: String
    }

    public typealias Factory = AppStateManagerFactory

    private let factory: Factory

    private lazy var appStateManager: AppStateManager = factory.makeAppStateManager()
    @Dependency(\.propertiesManager) private var propertiesManager
    @Dependency(\.vpnKeychain) private var vpnKeychain

    @SharedReader(.userCountry) var userCountry // these shared properties are not yet populated for mac, we should do that
    @SharedReader(.userISP) var userISP // these shared properties are not yet populated for mac, we should do that
    @SharedReader(.connectedAt) var connectedAt // these shared properties are not yet populated for mac, we should do that

    var networkType: ConnectionDimensions.NetworkType = .other
    var previousConnectionStatus: ConnectionStatus?
    var previousConnectionIntent: ServerConnectionIntent?

    var userInitiatedVPNChange: UserInitiatedVPNChange?

    private lazy var previousConnectionConfiguration: ConnectionConfiguration? = appStateManager.activeConnection()

    private let timer: TelemetryTimer

    private var telemetryEventScheduler: TelemetryEventScheduler
    private var businessEventScheduler: TelemetryEventScheduler

    init(
        factory: Factory,
        timer: TelemetryTimer = ConnectionTimer(),
        telemetryEventScheduler: TelemetryEventScheduler,
        businessEventScheduler: TelemetryEventScheduler
    ) async {
        self.factory = factory
        self.timer = timer

        self.telemetryEventScheduler = telemetryEventScheduler
        self.businessEventScheduler = businessEventScheduler
    }

    public func setNetworkType(_ type: ConnectionDimensions.NetworkType) {
        networkType = type
    }

    public func setUserInitiatedVPNChange(_ change: UserInitiatedVPNChange) {
        userInitiatedVPNChange = change
    }

    public func vpnGatewayConnectionChanged(_ connectionStatus: ConnectionStatus) async throws {
        // Assume the first status is generated by the system upon app launch
        guard previousConnectionStatus != nil else {
            previousConnectionStatus = connectionStatus
            let errorMessage = "`previousConnectionStatus` is nil, saving status and ignoring event: \(connectionStatus)"
            throw Error(localizedDescription: errorMessage)
        }
        defer {
            if [.connected, .disconnected, .connecting].contains(connectionStatus) {
                previousConnectionStatus = connectionStatus
            }
        }
        // appStateManager should be now initiated and should produce a correct connectedDate
        await timer.updateConnectionStarted(connectedAt)
        var eventType: ConnectionEvent.Event
        switch connectionStatus {
        case .connected:
            timer.markFinishedConnecting()
            eventType = try connectionEventType(state: connectionStatus)
        case .connecting:
            timer.markConnectionStopped()
            timer.markStartedConnecting()
            eventType = try connectionEventType(state: connectionStatus)
        case .disconnected:
            timer.markConnectionStopped()
            eventType = try connectionEventType(state: connectionStatus)
        case .disconnecting:
            throw Error(localizedDescription: "Ignoring the `disconnecting` status")
        }
        let event = try collectDimensions(
            outcome: connectionOutcome(connectionStatus),
            eventType: eventType
        )
        await scheduleEvent(event)
    }

    private func scheduleEvent(_ event: ConnectionEvent) async {
        do {
            try await telemetryEventScheduler.report(event: event)
        } catch {
            log.debug("\(error)", category: .telemetry)
        }
        do {
            try await businessEventScheduler.report(event: event)
        } catch {
            log.debug("\(error)", category: .telemetry)
        }
    }

    private func collectDimensions(outcome: ConnectionDimensions.Outcome, eventType: ConnectionEvent.Event?) throws -> ConnectionEvent {
        guard let eventType else {
            throw Error(localizedDescription: "Can't determine eventType")
        }
        guard let connection = connection(eventType: eventType) else {
            throw Error(localizedDescription: "No active connection")
        }
        guard let port = connection.ports.first else {
            throw Error(localizedDescription: "No port detected")
        }
        let dimensions = ConnectionDimensions(
            outcome: outcome,
            userTier: userTier(),
            vpnStatus: previousConnectionStatus == .connected ? .on : .off,
            vpnTrigger: vpnTrigger(eventType: eventType),
            networkType: networkType,
            serverFeatures: connection.server.feature,
            vpnCountry: connection.server.countryCode,
            userCountry: userCountry ?? "",
            protocol: connection.vpnProtocol,
            server: connection.server.name,
            port: String(port),
            isp: userISP ?? "",
            isServerFree: connection.server.isFree
        )
        if case .settingsChange = userInitiatedVPNChange,
           case .vpnDisconnection = eventType {
            // don't reset the `userInitiatedVPNChange` on disconnect, we'll need it in just a moment for the connection event
        } else {
            userInitiatedVPNChange = nil
            // reset the `userInitiatedVPNChange` so that consequent events that are not explicitly generated by the user are not overriden by this (now) stale value
        }
        previousConnectionConfiguration = appStateManager.activeConnection()
        return ConnectionEvent(event: eventType, dimensions: dimensions)
    }

    private enum ConnectionEventError: LocalizedError {
        case missingEventType
        case missingConnectionIntent
        case missingPort

        var localizedDescription: String {
            switch self {
            case .missingEventType:
                "Can't determine eventType"
            case .missingConnectionIntent:
                "No connection intent available"
            case .missingPort:
                "No port detected"
            }
        }
    }

    private func userTier() -> ConnectionDimensions.UserTier {
        let cached = try? vpnKeychain.fetchCached()
        let tier = cached?.maxTier ?? .freeTier
        if tier == .internalTier {
            return .internal
        }
        return tier.isFreeTier ? .free : .paid
    }

    private func connection(eventType: ConnectionEvent.Event) -> ConnectionConfiguration? {
        switch eventType {
        case .vpnConnection:
            appStateManager.activeConnection()
        case .vpnDisconnection:
            previousConnectionConfiguration
        }
    }

    private func connectionEventType(state: ConnectionStatus) throws -> ConnectionEvent.Event {
        switch state {
        case .connected:
            let timeInterval = try timer.timeToConnect
            return .vpnConnection(timeToConnection: timeInterval)
        case .disconnected:
            if previousConnectionStatus == .connected {
                return try .vpnDisconnection(sessionLength: timer.connectionDuration)
            } else if previousConnectionStatus == .connecting {
                return try .vpnConnection(timeToConnection: timer.timeConnecting)
            }
            throw Error(localizedDescription: "Ignoring disconnected event, was previously disconnected")
        case .connecting:
            if previousConnectionStatus == .connected {
                return try .vpnDisconnection(sessionLength: timer.connectionDuration)
            }
            throw Error(localizedDescription: "Ignoring connecting event, wasn't connected before")
        case .disconnecting:
            throw Error(localizedDescription: "Ignoring disconnecting state")
        }
    }

    private func connectionOutcome(_ state: ConnectionStatus) -> ConnectionDimensions.Outcome {
        switch state {
        case .disconnected:
            if [.connected, .connecting].contains(previousConnectionStatus) {
                guard let userInitiatedVPNChange else {
                    return .failure
                }
                switch userInitiatedVPNChange {
                case .connect, .disconnect:
                    return .success
                case .abort:
                    return .aborted
                case .settingsChange, .logout:
                    return .success
                }
            }
            return .success
        case .connected:
            return .success
        case .connecting:
            if previousConnectionStatus == .connected {
                return .success
            }
            return .failure
        case .disconnecting:
            return .failure
        }
    }

    private func vpnTrigger(eventType: ConnectionEvent.Event) -> UserInitiatedVPNChange.VPNTrigger {
        let newConnection: () -> UserInitiatedVPNChange.VPNTrigger = {
            if self.previousConnectionStatus == .connected,
               case .vpnDisconnection = eventType {
                return .newConnection
            }

            let lastConnectionTrigger = self.propertiesManager.lastConnectionRequest?.trigger
            return lastConnectionTrigger ?? .auto
        }

        guard let userInitiatedVPNChange else {
            return newConnection()
        }

        switch userInitiatedVPNChange {
        case let .connect(trigger):
            return trigger ?? newConnection()
        case let .disconnect(trigger):
            return trigger
        case .abort:
            return .auto
        case .settingsChange, .logout:
            return .auto
        }
    }
}
