// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(protunFFI)
    import protunFFI

    private extension RustBuffer {
        // Allocate a new buffer, copying the contents of a `UInt8` array.
        init(bytes: [UInt8]) {
            let rbuf = bytes.withUnsafeBufferPointer { ptr in
                RustBuffer.from(ptr)
            }
            self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
        }

        static func empty() -> RustBuffer {
            RustBuffer(capacity: 0, len: 0, data: nil)
        }

        static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
            try! rustCall { ffi_protun_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
        }

        // Frees the buffer in place.
        // The buffer must not be used after this is called.
        func deallocate() {
            try! rustCall { ffi_protun_rustbuffer_free(self, $0) }
        }
    }

    private extension ForeignBytes {
        init(bufferPointer: UnsafeBufferPointer<UInt8>) {
            self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
        }
    }

    // For every type used in the interface, we provide helper methods for conveniently
    // lifting and lowering that type from C-compatible data, and for reading and writing
    // values of that type in a buffer.

    // Helper classes/extensions that don't change.
    // Someday, this will be in a library of its own.

    private extension Data {
        init(rustBuffer: RustBuffer) {
            self.init(
                bytesNoCopy: rustBuffer.data!,
                count: Int(rustBuffer.len),
                deallocator: .none
            )
        }
    }

    // Define reader functionality.  Normally this would be defined in a class or
    // struct, but we use standalone functions instead in order to make external
    // types work.
//
    // With external types, one swift source file needs to be able to call the read
    // method on another source file's FfiConverter, but then what visibility
    // should Reader have?
    // - If Reader is fileprivate, then this means the read() must also
    //   be fileprivate, which doesn't work with external types.
    // - If Reader is internal/public, we'll get compile errors since both source
    //   files will try define the same type.
//
    // Instead, the read() method and these helper functions input a tuple of data

    private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
        (data: data, offset: 0)
    }

    // Reads an integer at the current offset, in big-endian order, and advances
    // the offset on success. Throws if reading the integer would move the
    // offset past the end of the buffer.
    private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
        let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
        guard reader.data.count >= range.upperBound else {
            throw UniffiInternalError.bufferOverflow
        }
        if T.self == UInt8.self {
            let value = reader.data[reader.offset]
            reader.offset += 1
            return value as! T
        }
        var value: T = 0
        let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
        reader.offset = range.upperBound
        return value.bigEndian
    }

    // Reads an arbitrary number of bytes, to be used to read
    // raw bytes, this is useful when lifting strings
    private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
        let range = reader.offset ..< (reader.offset + count)
        guard reader.data.count >= range.upperBound else {
            throw UniffiInternalError.bufferOverflow
        }
        var value = [UInt8](repeating: 0, count: count)
        value.withUnsafeMutableBufferPointer { buffer in
            reader.data.copyBytes(to: buffer, from: range)
        }
        reader.offset = range.upperBound
        return value
    }

    // Reads a float at the current offset.
    private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
        try Float(bitPattern: readInt(&reader))
    }

    // Reads a float at the current offset.
    private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
        try Double(bitPattern: readInt(&reader))
    }

    // Indicates if the offset has reached the end of the buffer.
    private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
        reader.offset < reader.data.count
    }

    // Define writer functionality.  Normally this would be defined in a class or
    // struct, but we use standalone functions instead in order to make external
    // types work.  See the above discussion on Readers for details.

    private func createWriter() -> [UInt8] {
        []
    }

    private func writeBytes(_ writer: inout [UInt8], _ byteArr: some Sequence<UInt8>) {
        writer.append(contentsOf: byteArr)
    }

    // Writes an integer in big-endian order.
//
    // Warning: make sure what you are trying to write
    // is in the correct type!
    private func writeInt(_ writer: inout [UInt8], _ value: some FixedWidthInteger) {
        var value = value.bigEndian
        withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
    }

    private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
        writeInt(&writer, value.bitPattern)
    }

    private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
        writeInt(&writer, value.bitPattern)
    }

    // Protocol for types that transfer other types across the FFI. This is
    // analogous to the Rust trait of the same name.
    private protocol FfiConverter {
        associatedtype FfiType
        associatedtype SwiftType

        static func lift(_ value: FfiType) throws -> SwiftType
        static func lower(_ value: SwiftType) -> FfiType
        static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
        static func write(_ value: SwiftType, into buf: inout [UInt8])
    }

    // Types conforming to `Primitive` pass themselves directly over the FFI.
    private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

    extension FfiConverterPrimitive {
        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        static func lift(_ value: FfiType) throws -> SwiftType {
            value
        }

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        static func lower(_ value: SwiftType) -> FfiType {
            value
        }
    }

    // Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
    // Used for complex types where it's hard to write a custom lift/lower.
    private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

    extension FfiConverterRustBuffer {
        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        static func lift(_ buf: RustBuffer) throws -> SwiftType {
            var reader = createReader(data: Data(rustBuffer: buf))
            let value = try read(from: &reader)
            if hasRemaining(reader) {
                throw UniffiInternalError.incompleteData
            }
            buf.deallocate()
            return value
        }

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        static func lower(_ value: SwiftType) -> RustBuffer {
            var writer = createWriter()
            write(value, into: &writer)
            return RustBuffer(bytes: writer)
        }
    }

    // An error type for FFI errors. These errors occur at the UniFFI level, not
    // the library level.
    private enum UniffiInternalError: LocalizedError {
        case bufferOverflow
        case incompleteData
        case unexpectedOptionalTag
        case unexpectedEnumCase
        case unexpectedNullPointer
        case unexpectedRustCallStatusCode
        case unexpectedRustCallError
        case unexpectedStaleHandle
        case rustPanic(_ message: String)

        public var errorDescription: String? {
            switch self {
            case .bufferOverflow: "Reading the requested value would read past the end of the buffer"
            case .incompleteData: "The buffer still has data after lifting its containing value"
            case .unexpectedOptionalTag: "Unexpected optional tag; should be 0 or 1"
            case .unexpectedEnumCase: "Raw enum value doesn't match any cases"
            case .unexpectedNullPointer: "Raw pointer value was null"
            case .unexpectedRustCallStatusCode: "Unexpected RustCallStatus code"
            case .unexpectedRustCallError: "CALL_ERROR but no errorClass specified"
            case .unexpectedStaleHandle: "The object in the handle map has been dropped already"
            case let .rustPanic(message): message
            }
        }
    }

    private extension NSLock {
        func withLock<T>(f: () throws -> T) rethrows -> T {
            lock()
            defer { self.unlock() }
            return try f()
        }
    }

    private let CALL_SUCCESS: Int8 = 0
    private let CALL_ERROR: Int8 = 1
    private let CALL_UNEXPECTED_ERROR: Int8 = 2
    private let CALL_CANCELLED: Int8 = 3

    private extension RustCallStatus {
        init() {
            self.init(
                code: CALL_SUCCESS,
                errorBuf: RustBuffer(
                    capacity: 0,
                    len: 0,
                    data: nil
                )
            )
        }
    }

    private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
        let neverThrow: ((RustBuffer) throws -> Never)? = nil
        return try makeRustCall(callback, errorHandler: neverThrow)
    }

    private func rustCallWithError<T>(
        _ errorHandler: @escaping (RustBuffer) throws -> some Swift.Error,
        _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
    ) throws -> T {
        try makeRustCall(callback, errorHandler: errorHandler)
    }

    private func makeRustCall<T>(
        _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
        errorHandler: ((RustBuffer) throws -> some Swift.Error)?
    ) throws -> T {
        uniffiEnsureProtunInitialized()
        var callStatus = RustCallStatus()
        let returnedVal = callback(&callStatus)
        try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
        return returnedVal
    }

    private func uniffiCheckCallStatus(
        callStatus: RustCallStatus,
        errorHandler: ((RustBuffer) throws -> some Swift.Error)?
    ) throws {
        switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
        }
    }

    private func uniffiTraitInterfaceCall<T>(
        callStatus: UnsafeMutablePointer<RustCallStatus>,
        makeCall: () throws -> T,
        writeReturn: (T) -> Void
    ) {
        do {
            try writeReturn(makeCall())
        } catch {
            callStatus.pointee.code = CALL_UNEXPECTED_ERROR
            callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
        }
    }

    private func uniffiTraitInterfaceCallWithError<T, E>(
        callStatus: UnsafeMutablePointer<RustCallStatus>,
        makeCall: () throws -> T,
        writeReturn: (T) -> Void,
        lowerError: (E) -> RustBuffer
    ) {
        do {
            try writeReturn(makeCall())
        } catch let error as E {
            callStatus.pointee.code = CALL_ERROR
            callStatus.pointee.errorBuf = lowerError(error)
        } catch {
            callStatus.pointee.code = CALL_UNEXPECTED_ERROR
            callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
        }
    }

    private final class UniffiHandleMap<T>: @unchecked Sendable {
        // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
        private let lock = NSLock()
        private var map: [UInt64: T] = [:]
        private var currentHandle: UInt64 = 1

        func insert(obj: T) -> UInt64 {
            lock.withLock {
                let handle = currentHandle
                currentHandle += 1
                map[handle] = obj
                return handle
            }
        }

        func get(handle: UInt64) throws -> T {
            try lock.withLock {
                guard let obj = map[handle] else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return obj
            }
        }

        @discardableResult
        func remove(handle: UInt64) throws -> T {
            try lock.withLock {
                guard let obj = map.removeValue(forKey: handle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return obj
            }
        }

        var count: Int {
            map.count
        }
    }

    // Public interface members begin here.
    // Magic number for the Rust proxy to call using the same mechanism as every other method,
    // to free the callback once it's dropped by Rust.
    private let IDX_CALLBACK_FREE: Int32 = 0
    // Callback return codes
    private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
    private let UNIFFI_CALLBACK_ERROR: Int32 = 1
    private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private struct FfiConverterUInt16: FfiConverterPrimitive {
        typealias FfiType = UInt16
        typealias SwiftType = UInt16

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
            try lift(readInt(&buf))
        }

        public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
            writeInt(&buf, lower(value))
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private struct FfiConverterInt32: FfiConverterPrimitive {
        typealias FfiType = Int32
        typealias SwiftType = Int32

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
            try lift(readInt(&buf))
        }

        public static func write(_ value: Int32, into buf: inout [UInt8]) {
            writeInt(&buf, lower(value))
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private struct FfiConverterBool: FfiConverter {
        typealias FfiType = Int8
        typealias SwiftType = Bool

        public static func lift(_ value: Int8) throws -> Bool {
            value != 0
        }

        public static func lower(_ value: Bool) -> Int8 {
            value ? 1 : 0
        }

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
            try lift(readInt(&buf))
        }

        public static func write(_ value: Bool, into buf: inout [UInt8]) {
            writeInt(&buf, lower(value))
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private struct FfiConverterString: FfiConverter {
        typealias SwiftType = String
        typealias FfiType = RustBuffer

        public static func lift(_ value: RustBuffer) throws -> String {
            defer {
                value.deallocate()
            }
            if value.data == nil {
                return String()
            }
            let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
            return String(bytes: bytes, encoding: String.Encoding.utf8)!
        }

        public static func lower(_ value: String) -> RustBuffer {
            value.utf8CString.withUnsafeBufferPointer { ptr in
                // The swift string gives us int8_t, we want uint8_t.
                ptr.withMemoryRebound(to: UInt8.self) { ptr in
                    // The swift string gives us a trailing null byte, we don't want it.
                    let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                    return RustBuffer.from(buf)
                }
            }
        }

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
            let len: Int32 = try readInt(&buf)
            return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
        }

        public static func write(_ value: String, into buf: inout [UInt8]) {
            let len = Int32(value.utf8.count)
            writeInt(&buf, len)
            writeBytes(&buf, value.utf8)
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private struct FfiConverterData: FfiConverterRustBuffer {
        typealias SwiftType = Data

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
            let len: Int32 = try readInt(&buf)
            return try Data(readBytes(&buf, count: Int(len)))
        }

        public static func write(_ value: Data, into buf: inout [UInt8]) {
            let len = Int32(value.count)
            writeInt(&buf, len)
            writeBytes(&buf, value)
        }
    }

    /**
     * Represents an active VPN connection.
     * Platform-specific constructor (::*_connect) is defined in dedicated module
     * (see e.g. [crate::api::connection_unix]). Helper constructor capturing common logic
     * ([Connection::connect_internal]) is added for convenience.
     *
     * Connection will make a best effort to maintain VPN connection cycling through a set of candidate peers
     * (along with ports and protocols) based on their priority and availability in current network conditions.
     *
     * Connection can run in two modes:
     * - with built-in local agent: when client passes [LocalAgentClientCert] != None.
     * - without local agent: [LocalAgentClientCert] == None
     *
     * Local agent mode is available when `local-agent` feature is enabled.
     *
     * In local-agent mode, after establishing VPN connection via e.g. WireGuard, LocalAgentConnection will
     * be established before Connection enters connected state.
     *
     * In non-local-agent mode, Connection will enter connected state immediately after establishing VPN connection.
     *
     * For initializing logging, see [crate::api::logger::init_logger].
     */
    public protocol ConnectionProtocol: AnyObject, Sendable {
        /**
         * Disconnects. Connection should not be used after this.
         */
        func disconnect()

        /**
         * Call it when connectivity or underlying network adapter(s) change
         * (e.g. network switched from wifi to mobile). Library will use that information
         * to reset VPN connection sockets.
         */
        func onSetNetworkAvailable(isNetworkAvailable: Bool)

        /**
         * Updates candidate peers for connection.
         * Method call might not necessarily result in new connection if suitable peer is already connected.
         */
        func updatePeers(peers: [PeerInfo])

        /**
         * Notifies library that file descriptor for tun device has changed.
         */
        func updateUnixTun(tunFd: Int32)

        /**
         * Updates WireGuard private key.
         */
        func updateWgPrivateKey(info: PrivateKeyUpdateInfo)
    }

    /**
     * Represents an active VPN connection.
     * Platform-specific constructor (::*_connect) is defined in dedicated module
     * (see e.g. [crate::api::connection_unix]). Helper constructor capturing common logic
     * ([Connection::connect_internal]) is added for convenience.
     *
     * Connection will make a best effort to maintain VPN connection cycling through a set of candidate peers
     * (along with ports and protocols) based on their priority and availability in current network conditions.
     *
     * Connection can run in two modes:
     * - with built-in local agent: when client passes [LocalAgentClientCert] != None.
     * - without local agent: [LocalAgentClientCert] == None
     *
     * Local agent mode is available when `local-agent` feature is enabled.
     *
     * In local-agent mode, after establishing VPN connection via e.g. WireGuard, LocalAgentConnection will
     * be established before Connection enters connected state.
     *
     * In non-local-agent mode, Connection will enter connected state immediately after establishing VPN connection.
     *
     * For initializing logging, see [crate::api::logger::init_logger].
     */
    open class Connection: ConnectionProtocol, @unchecked Sendable {
        fileprivate let pointer: UnsafeMutableRawPointer!

        /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public struct NoPointer {
            public init() {}
        }

        // TODO: We'd like this to be `private` but for Swifty reasons,
        // we can't implement `FfiConverter` without making this `required` and we can't
        // make it `required` without making it `public`.
        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
            self.pointer = pointer
        }

        // This constructor can be used to instantiate a fake object.
        // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
        //
        // - Warning:
        //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public init(noPointer _: NoPointer) {
            self.pointer = nil
        }

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public func uniffiClonePointer() -> UnsafeMutableRawPointer {
            try! rustCall { uniffi_protun_fn_clone_connection(self.pointer, $0) }
        }

        // No primary constructor declared for this class.

        deinit {
            guard let pointer else {
                return
            }

            try! rustCall { uniffi_protun_fn_free_connection(pointer, $0) }
        }

        /**
         * Unix-specific constructor for Connection.
         * Expects file descriptor of tun device that Connection will take ownership of.
         */
        public static func unixConnect(config: InitialConnectionConfig, tunFd: Int32, stateChangeCallback: StateChangedCallback, socketFdAvailableCallback: OnSocketFdAvailableCallback?) -> Connection {
            try! FfiConverterTypeConnection_lift(try! rustCall {
                uniffi_protun_fn_constructor_connection_unix_connect(
                    FfiConverterTypeInitialConnectionConfig_lower(config),
                    FfiConverterInt32.lower(tunFd),
                    FfiConverterCallbackInterfaceStateChangedCallback_lower(stateChangeCallback),
                    FfiConverterOptionCallbackInterfaceOnSocketFdAvailableCallback.lower(socketFdAvailableCallback), $0
                )
            })
        }

        /**
         * Disconnects. Connection should not be used after this.
         */
        open func disconnect() { try! rustCall {
            uniffi_protun_fn_method_connection_disconnect(
                self.uniffiClonePointer(),
                $0
            )
        }
        }

        /**
         * Call it when connectivity or underlying network adapter(s) change
         * (e.g. network switched from wifi to mobile). Library will use that information
         * to reset VPN connection sockets.
         */
        open func onSetNetworkAvailable(isNetworkAvailable: Bool) { try! rustCall {
            uniffi_protun_fn_method_connection_on_set_network_available(
                self.uniffiClonePointer(),
                FfiConverterBool.lower(isNetworkAvailable),
                $0
            )
        }
        }

        /**
         * Updates candidate peers for connection.
         * Method call might not necessarily result in new connection if suitable peer is already connected.
         */
        open func updatePeers(peers: [PeerInfo]) { try! rustCall {
            uniffi_protun_fn_method_connection_update_peers(
                self.uniffiClonePointer(),
                FfiConverterSequenceTypePeerInfo.lower(peers),
                $0
            )
        }
        }

        /**
         * Notifies library that file descriptor for tun device has changed.
         */
        open func updateUnixTun(tunFd: Int32) { try! rustCall {
            uniffi_protun_fn_method_connection_update_unix_tun(
                self.uniffiClonePointer(),
                FfiConverterInt32.lower(tunFd),
                $0
            )
        }
        }

        /**
         * Updates WireGuard private key.
         */
        open func updateWgPrivateKey(info: PrivateKeyUpdateInfo) { try! rustCall {
            uniffi_protun_fn_method_connection_update_wg_private_key(
                self.uniffiClonePointer(),
                FfiConverterTypePrivateKeyUpdateInfo_lower(info),
                $0
            )
        }
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypeConnection: FfiConverter {
        typealias FfiType = UnsafeMutableRawPointer
        typealias SwiftType = Connection

        public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Connection {
            Connection(unsafeFromRawPointer: pointer)
        }

        public static func lower(_ value: Connection) -> UnsafeMutableRawPointer {
            value.uniffiClonePointer()
        }

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Connection {
            let v: UInt64 = try readInt(&buf)
            // The Rust code won't compile if a pointer won't fit in a UInt64.
            // We have to go via `UInt` because that's the thing that's the size of a pointer.
            let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
            if ptr == nil {
                throw UniffiInternalError.unexpectedNullPointer
            }
            return try lift(ptr!)
        }

        public static func write(_ value: Connection, into buf: inout [UInt8]) {
            // This fiddling is because `Int` is the thing that's the same size as a pointer.
            // The Rust code won't compile if a pointer won't fit in a `UInt64`.
            writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeConnection_lift(_ pointer: UnsafeMutableRawPointer) throws -> Connection {
        try FfiConverterTypeConnection.lift(pointer)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeConnection_lower(_ value: Connection) -> UnsafeMutableRawPointer {
        FfiConverterTypeConnection.lower(value)
    }

    public struct InitialConnectionConfig {
        public var wgPrivateKey: WgClientPrivateKey
        public var peers: [PeerInfo]
        public var networkAvailable: Bool

        // Default memberwise initializers are never public by default, so we
        // declare one manually.
        public init(wgPrivateKey: WgClientPrivateKey, peers: [PeerInfo], networkAvailable: Bool) {
            self.wgPrivateKey = wgPrivateKey
            self.peers = peers
            self.networkAvailable = networkAvailable
        }
    }

    #if compiler(>=6)
        extension InitialConnectionConfig: Sendable {}
    #endif

    extension InitialConnectionConfig: Equatable, Hashable {
        public static func == (lhs: InitialConnectionConfig, rhs: InitialConnectionConfig) -> Bool {
            if lhs.wgPrivateKey != rhs.wgPrivateKey {
                return false
            }
            if lhs.peers != rhs.peers {
                return false
            }
            if lhs.networkAvailable != rhs.networkAvailable {
                return false
            }
            return true
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(wgPrivateKey)
            hasher.combine(peers)
            hasher.combine(networkAvailable)
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypeInitialConnectionConfig: FfiConverterRustBuffer {
        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InitialConnectionConfig {
            try InitialConnectionConfig(
                wgPrivateKey: FfiConverterTypeWgClientPrivateKey.read(from: &buf),
                peers: FfiConverterSequenceTypePeerInfo.read(from: &buf),
                networkAvailable: FfiConverterBool.read(from: &buf)
            )
        }

        public static func write(_ value: InitialConnectionConfig, into buf: inout [UInt8]) {
            FfiConverterTypeWgClientPrivateKey.write(value.wgPrivateKey, into: &buf)
            FfiConverterSequenceTypePeerInfo.write(value.peers, into: &buf)
            FfiConverterBool.write(value.networkAvailable, into: &buf)
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeInitialConnectionConfig_lift(_ buf: RustBuffer) throws -> InitialConnectionConfig {
        try FfiConverterTypeInitialConnectionConfig.lift(buf)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeInitialConnectionConfig_lower(_ value: InitialConnectionConfig) -> RustBuffer {
        FfiConverterTypeInitialConnectionConfig.lower(value)
    }

    public struct PeerConnectionInfo {
        public var peerId: String
        public var entryIp: String
        public var `protocol`: Protocol
        public var port: UInt16

        // Default memberwise initializers are never public by default, so we
        // declare one manually.
        public init(peerId: String, entryIp: String, protocol: Protocol, port: UInt16) {
            self.peerId = peerId
            self.entryIp = entryIp
            self.protocol = `protocol`
            self.port = port
        }
    }

    #if compiler(>=6)
        extension PeerConnectionInfo: Sendable {}
    #endif

    extension PeerConnectionInfo: Equatable, Hashable {
        public static func == (lhs: PeerConnectionInfo, rhs: PeerConnectionInfo) -> Bool {
            if lhs.peerId != rhs.peerId {
                return false
            }
            if lhs.entryIp != rhs.entryIp {
                return false
            }
            if lhs.protocol != rhs.protocol {
                return false
            }
            if lhs.port != rhs.port {
                return false
            }
            return true
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(peerId)
            hasher.combine(entryIp)
            hasher.combine(`protocol`)
            hasher.combine(port)
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypePeerConnectionInfo: FfiConverterRustBuffer {
        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PeerConnectionInfo {
            try PeerConnectionInfo(
                peerId: FfiConverterString.read(from: &buf),
                entryIp: FfiConverterString.read(from: &buf),
                protocol: FfiConverterTypeProtocol.read(from: &buf),
                port: FfiConverterUInt16.read(from: &buf)
            )
        }

        public static func write(_ value: PeerConnectionInfo, into buf: inout [UInt8]) {
            FfiConverterString.write(value.peerId, into: &buf)
            FfiConverterString.write(value.entryIp, into: &buf)
            FfiConverterTypeProtocol.write(value.protocol, into: &buf)
            FfiConverterUInt16.write(value.port, into: &buf)
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypePeerConnectionInfo_lift(_ buf: RustBuffer) throws -> PeerConnectionInfo {
        try FfiConverterTypePeerConnectionInfo.lift(buf)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypePeerConnectionInfo_lower(_ value: PeerConnectionInfo) -> RustBuffer {
        FfiConverterTypePeerConnectionInfo.lower(value)
    }

    /**
     * Represents a candidate peer for connection.
     */
    public struct PeerInfo {
        /**
         * Unique identifier of connected peer (as defined by client). This id will be available in
         * connection states when given peer is connecting/connected (see peer_id in [State]).
         */
        public var peerId: String
        public var serverIp: IpAddress
        public var serverPublicKey: WgPeerPublicKey
        public var udpPorts: [UInt16]
        public var tcpPorts: [UInt16]
        public var tlsPorts: [UInt16]
        public var priority: Int32

        // Default memberwise initializers are never public by default, so we
        // declare one manually.
        public init(
            /**
             * Unique identifier of connected peer (as defined by client). This id will be available in
             * connection states when given peer is connecting/connected (see peer_id in [State]).
             */ peerId: String, serverIp: IpAddress, serverPublicKey: WgPeerPublicKey, udpPorts: [UInt16], tcpPorts: [UInt16], tlsPorts: [UInt16], priority: Int32
        ) {
            self.peerId = peerId
            self.serverIp = serverIp
            self.serverPublicKey = serverPublicKey
            self.udpPorts = udpPorts
            self.tcpPorts = tcpPorts
            self.tlsPorts = tlsPorts
            self.priority = priority
        }
    }

    #if compiler(>=6)
        extension PeerInfo: Sendable {}
    #endif

    extension PeerInfo: Equatable, Hashable {
        public static func == (lhs: PeerInfo, rhs: PeerInfo) -> Bool {
            if lhs.peerId != rhs.peerId {
                return false
            }
            if lhs.serverIp != rhs.serverIp {
                return false
            }
            if lhs.serverPublicKey != rhs.serverPublicKey {
                return false
            }
            if lhs.udpPorts != rhs.udpPorts {
                return false
            }
            if lhs.tcpPorts != rhs.tcpPorts {
                return false
            }
            if lhs.tlsPorts != rhs.tlsPorts {
                return false
            }
            if lhs.priority != rhs.priority {
                return false
            }
            return true
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(peerId)
            hasher.combine(serverIp)
            hasher.combine(serverPublicKey)
            hasher.combine(udpPorts)
            hasher.combine(tcpPorts)
            hasher.combine(tlsPorts)
            hasher.combine(priority)
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypePeerInfo: FfiConverterRustBuffer {
        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PeerInfo {
            try PeerInfo(
                peerId: FfiConverterString.read(from: &buf),
                serverIp: FfiConverterTypeIpAddress.read(from: &buf),
                serverPublicKey: FfiConverterTypeWgPeerPublicKey.read(from: &buf),
                udpPorts: FfiConverterSequenceUInt16.read(from: &buf),
                tcpPorts: FfiConverterSequenceUInt16.read(from: &buf),
                tlsPorts: FfiConverterSequenceUInt16.read(from: &buf),
                priority: FfiConverterInt32.read(from: &buf)
            )
        }

        public static func write(_ value: PeerInfo, into buf: inout [UInt8]) {
            FfiConverterString.write(value.peerId, into: &buf)
            FfiConverterTypeIpAddress.write(value.serverIp, into: &buf)
            FfiConverterTypeWgPeerPublicKey.write(value.serverPublicKey, into: &buf)
            FfiConverterSequenceUInt16.write(value.udpPorts, into: &buf)
            FfiConverterSequenceUInt16.write(value.tcpPorts, into: &buf)
            FfiConverterSequenceUInt16.write(value.tlsPorts, into: &buf)
            FfiConverterInt32.write(value.priority, into: &buf)
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypePeerInfo_lift(_ buf: RustBuffer) throws -> PeerInfo {
        try FfiConverterTypePeerInfo.lift(buf)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypePeerInfo_lower(_ value: PeerInfo) -> RustBuffer {
        FfiConverterTypePeerInfo.lower(value)
    }

    public struct PrivateKeyUpdateInfo {
        public var wgPrivateKey: WgClientPrivateKey

        // Default memberwise initializers are never public by default, so we
        // declare one manually.
        public init(wgPrivateKey: WgClientPrivateKey) {
            self.wgPrivateKey = wgPrivateKey
        }
    }

    #if compiler(>=6)
        extension PrivateKeyUpdateInfo: Sendable {}
    #endif

    extension PrivateKeyUpdateInfo: Equatable, Hashable {
        public static func == (lhs: PrivateKeyUpdateInfo, rhs: PrivateKeyUpdateInfo) -> Bool {
            if lhs.wgPrivateKey != rhs.wgPrivateKey {
                return false
            }
            return true
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(wgPrivateKey)
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypePrivateKeyUpdateInfo: FfiConverterRustBuffer {
        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PrivateKeyUpdateInfo {
            try PrivateKeyUpdateInfo(
                wgPrivateKey: FfiConverterTypeWgClientPrivateKey.read(from: &buf)
            )
        }

        public static func write(_ value: PrivateKeyUpdateInfo, into buf: inout [UInt8]) {
            FfiConverterTypeWgClientPrivateKey.write(value.wgPrivateKey, into: &buf)
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypePrivateKeyUpdateInfo_lift(_ buf: RustBuffer) throws -> PrivateKeyUpdateInfo {
        try FfiConverterTypePrivateKeyUpdateInfo.lift(buf)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypePrivateKeyUpdateInfo_lower(_ value: PrivateKeyUpdateInfo) -> RustBuffer {
        FfiConverterTypePrivateKeyUpdateInfo.lower(value)
    }

    // Note that we don't yet support `indirect` for enums.
    // See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

    public enum DisconnectReason {
        /**
         * There was a problem establishing TUN interface.
         */
        case tunEstablishError(message: String
        )
    }

    #if compiler(>=6)
        extension DisconnectReason: Sendable {}
    #endif

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypeDisconnectReason: FfiConverterRustBuffer {
        typealias SwiftType = DisconnectReason

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DisconnectReason {
            let variant: Int32 = try readInt(&buf)
            switch variant {
            case 1: return try .tunEstablishError(message: FfiConverterString.read(from: &buf)
                )

            default: throw UniffiInternalError.unexpectedEnumCase
            }
        }

        public static func write(_ value: DisconnectReason, into buf: inout [UInt8]) {
            switch value {
            case let .tunEstablishError(message):
                writeInt(&buf, Int32(1))
                FfiConverterString.write(message, into: &buf)
            }
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeDisconnectReason_lift(_ buf: RustBuffer) throws -> DisconnectReason {
        try FfiConverterTypeDisconnectReason.lift(buf)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeDisconnectReason_lower(_ value: DisconnectReason) -> RustBuffer {
        FfiConverterTypeDisconnectReason.lower(value)
    }

    extension DisconnectReason: Equatable, Hashable {}

    // Note that we don't yet support `indirect` for enums.
    // See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

    public enum LogLevel {
        case trace
        case debug
        case info
        case warn
        case error
    }

    #if compiler(>=6)
        extension LogLevel: Sendable {}
    #endif

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypeLogLevel: FfiConverterRustBuffer {
        typealias SwiftType = LogLevel

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LogLevel {
            let variant: Int32 = try readInt(&buf)
            switch variant {
            case 1: return .trace

            case 2: return .debug

            case 3: return .info

            case 4: return .warn

            case 5: return .error

            default: throw UniffiInternalError.unexpectedEnumCase
            }
        }

        public static func write(_ value: LogLevel, into buf: inout [UInt8]) {
            switch value {
            case .trace:
                writeInt(&buf, Int32(1))

            case .debug:
                writeInt(&buf, Int32(2))

            case .info:
                writeInt(&buf, Int32(3))

            case .warn:
                writeInt(&buf, Int32(4))

            case .error:
                writeInt(&buf, Int32(5))
            }
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeLogLevel_lift(_ buf: RustBuffer) throws -> LogLevel {
        try FfiConverterTypeLogLevel.lift(buf)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeLogLevel_lower(_ value: LogLevel) -> RustBuffer {
        FfiConverterTypeLogLevel.lower(value)
    }

    extension LogLevel: Equatable, Hashable {}

    // Note that we don't yet support `indirect` for enums.
    // See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

    public enum Protocol {
        case wireguardUdp
        case wireguardTcp
        case stealth
    }

    #if compiler(>=6)
        extension Protocol: Sendable {}
    #endif

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypeProtocol: FfiConverterRustBuffer {
        typealias SwiftType = Protocol

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Protocol {
            let variant: Int32 = try readInt(&buf)
            switch variant {
            case 1: return .wireguardUdp

            case 2: return .wireguardTcp

            case 3: return .stealth

            default: throw UniffiInternalError.unexpectedEnumCase
            }
        }

        public static func write(_ value: Protocol, into buf: inout [UInt8]) {
            switch value {
            case .wireguardUdp:
                writeInt(&buf, Int32(1))

            case .wireguardTcp:
                writeInt(&buf, Int32(2))

            case .stealth:
                writeInt(&buf, Int32(3))
            }
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeProtocol_lift(_ buf: RustBuffer) throws -> Protocol {
        try FfiConverterTypeProtocol.lift(buf)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeProtocol_lower(_ value: Protocol) -> RustBuffer {
        FfiConverterTypeProtocol.lower(value)
    }

    extension Protocol: Equatable, Hashable {}

    // Note that we don't yet support `indirect` for enums.
    // See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
    /**
     * State of the VPN connection.
     */

    public enum State {
        /**
         * Disconnected. [error] will be set if disconnection happened due to an error.
         */
        case disconnected(error: DisconnectReason?
        )
        /**
         * Library is attempting VPN connection to one or more candidate peers.
         */
        case connecting(peers: [PeerConnectionInfo]
        )
        /**
         * Library connection attempt requires app, user or system action to proceed.
         */
        case waitingForAction(reason: WaitReason
        )
        /**
         * Connection to [peer] is established.
         */
        case connected(peer: PeerConnectionInfo
        )
    }

    #if compiler(>=6)
        extension State: Sendable {}
    #endif

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypeState: FfiConverterRustBuffer {
        typealias SwiftType = State

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> State {
            let variant: Int32 = try readInt(&buf)
            switch variant {
            case 1: return try .disconnected(error: FfiConverterOptionTypeDisconnectReason.read(from: &buf)
                )

            case 2: return try .connecting(peers: FfiConverterSequenceTypePeerConnectionInfo.read(from: &buf)
                )

            case 3: return try .waitingForAction(reason: FfiConverterTypeWaitReason.read(from: &buf)
                )

            case 4: return try .connected(peer: FfiConverterTypePeerConnectionInfo.read(from: &buf)
                )

            default: throw UniffiInternalError.unexpectedEnumCase
            }
        }

        public static func write(_ value: State, into buf: inout [UInt8]) {
            switch value {
            case let .disconnected(error):
                writeInt(&buf, Int32(1))
                FfiConverterOptionTypeDisconnectReason.write(error, into: &buf)

            case let .connecting(peers):
                writeInt(&buf, Int32(2))
                FfiConverterSequenceTypePeerConnectionInfo.write(peers, into: &buf)

            case let .waitingForAction(reason):
                writeInt(&buf, Int32(3))
                FfiConverterTypeWaitReason.write(reason, into: &buf)

            case let .connected(peer):
                writeInt(&buf, Int32(4))
                FfiConverterTypePeerConnectionInfo.write(peer, into: &buf)
            }
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeState_lift(_ buf: RustBuffer) throws -> State {
        try FfiConverterTypeState.lift(buf)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeState_lower(_ value: State) -> RustBuffer {
        FfiConverterTypeState.lower(value)
    }

    extension State: Equatable, Hashable {}

    // Note that we don't yet support `indirect` for enums.
    // See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

    public enum WaitReason {
        /**
         * Device currently has no network (airplane mode, no signal, etc.)
         */
        case waitingForNetwork
        /**
         * There is I/O problem with TUN interface. Calling code might need to wait, recreate TUN or
         * disconnect (when it was caused by connection by another VPN app).
         */
        case tunIoError(message: String
        )
    }

    #if compiler(>=6)
        extension WaitReason: Sendable {}
    #endif

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypeWaitReason: FfiConverterRustBuffer {
        typealias SwiftType = WaitReason

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WaitReason {
            let variant: Int32 = try readInt(&buf)
            switch variant {
            case 1: return .waitingForNetwork

            case 2: return try .tunIoError(message: FfiConverterString.read(from: &buf)
                )

            default: throw UniffiInternalError.unexpectedEnumCase
            }
        }

        public static func write(_ value: WaitReason, into buf: inout [UInt8]) {
            switch value {
            case .waitingForNetwork:
                writeInt(&buf, Int32(1))

            case let .tunIoError(message):
                writeInt(&buf, Int32(2))
                FfiConverterString.write(message, into: &buf)
            }
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeWaitReason_lift(_ buf: RustBuffer) throws -> WaitReason {
        try FfiConverterTypeWaitReason.lift(buf)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeWaitReason_lower(_ value: WaitReason) -> RustBuffer {
        FfiConverterTypeWaitReason.lower(value)
    }

    extension WaitReason: Equatable, Hashable {}

    public protocol ClientLogger: AnyObject, Sendable {
        func log(level: LogLevel, message: String)
    }

    // Put the implementation in a struct so we don't pollute the top-level namespace
    private enum UniffiCallbackInterfaceClientLogger {
        // Create the VTable using a series of closures.
        // Swift automatically converts these into C callback functions.
        //
        // This creates 1-element array, since this seems to be the only way to construct a const
        // pointer that we can pass to the Rust code.
        static let vtable: [UniffiVTableCallbackInterfaceClientLogger] = [UniffiVTableCallbackInterfaceClientLogger(
            log: { (
                uniffiHandle: UInt64,
                level: RustBuffer,
                message: RustBuffer,
                _: UnsafeMutableRawPointer,
                uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
            ) in
                let makeCall = {
                    () throws in
                    guard let uniffiObj = try? FfiConverterCallbackInterfaceClientLogger.handleMap.get(handle: uniffiHandle) else {
                        throw UniffiInternalError.unexpectedStaleHandle
                    }
                    return try uniffiObj.log(
                        level: FfiConverterTypeLogLevel_lift(level),
                        message: FfiConverterString.lift(message)
                    )
                }

                let writeReturn = { () }
                uniffiTraitInterfaceCall(
                    callStatus: uniffiCallStatus,
                    makeCall: makeCall,
                    writeReturn: writeReturn
                )
            },
            uniffiFree: { (uniffiHandle: UInt64) in
                let result = try? FfiConverterCallbackInterfaceClientLogger.handleMap.remove(handle: uniffiHandle)
                if result == nil {
                    print("Uniffi callback interface ClientLogger: handle missing in uniffiFree")
                }
            }
        )]
    }

    private func uniffiCallbackInitClientLogger() {
        uniffi_protun_fn_init_callback_vtable_clientlogger(UniffiCallbackInterfaceClientLogger.vtable)
    }

    // FfiConverter protocol for callback interfaces
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private enum FfiConverterCallbackInterfaceClientLogger {
        fileprivate static let handleMap = UniffiHandleMap<ClientLogger>()
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    extension FfiConverterCallbackInterfaceClientLogger: FfiConverter {
        typealias SwiftType = ClientLogger
        typealias FfiType = UInt64

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public static func lift(_ handle: UInt64) throws -> SwiftType {
            try handleMap.get(handle: handle)
        }

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
            let handle: UInt64 = try readInt(&buf)
            return try lift(handle)
        }

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public static func lower(_ v: SwiftType) -> UInt64 {
            handleMap.insert(obj: v)
        }

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
            writeInt(&buf, lower(v))
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterCallbackInterfaceClientLogger_lift(_ handle: UInt64) throws -> ClientLogger {
        try FfiConverterCallbackInterfaceClientLogger.lift(handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterCallbackInterfaceClientLogger_lower(_ v: ClientLogger) -> UInt64 {
        FfiConverterCallbackInterfaceClientLogger.lower(v)
    }

    /**
     * Platform callback to notify that server connection socket file descriptor is available.
     * Android uses it to protect server connection socket from being routed via tun device.
     */
    public protocol OnSocketFdAvailableCallback: AnyObject, Sendable {
        func onSocketFdAvailable(socketFd: Int32)
    }

    // Put the implementation in a struct so we don't pollute the top-level namespace
    private enum UniffiCallbackInterfaceOnSocketFdAvailableCallback {
        // Create the VTable using a series of closures.
        // Swift automatically converts these into C callback functions.
        //
        // This creates 1-element array, since this seems to be the only way to construct a const
        // pointer that we can pass to the Rust code.
        static let vtable: [UniffiVTableCallbackInterfaceOnSocketFdAvailableCallback] = [UniffiVTableCallbackInterfaceOnSocketFdAvailableCallback(
            onSocketFdAvailable: { (
                uniffiHandle: UInt64,
                socketFd: Int32,
                _: UnsafeMutableRawPointer,
                uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
            ) in
                let makeCall = {
                    () throws in
                    guard let uniffiObj = try? FfiConverterCallbackInterfaceOnSocketFdAvailableCallback.handleMap.get(handle: uniffiHandle) else {
                        throw UniffiInternalError.unexpectedStaleHandle
                    }
                    return try uniffiObj.onSocketFdAvailable(
                        socketFd: FfiConverterInt32.lift(socketFd)
                    )
                }

                let writeReturn = { () }
                uniffiTraitInterfaceCall(
                    callStatus: uniffiCallStatus,
                    makeCall: makeCall,
                    writeReturn: writeReturn
                )
            },
            uniffiFree: { (uniffiHandle: UInt64) in
                let result = try? FfiConverterCallbackInterfaceOnSocketFdAvailableCallback.handleMap.remove(handle: uniffiHandle)
                if result == nil {
                    print("Uniffi callback interface OnSocketFdAvailableCallback: handle missing in uniffiFree")
                }
            }
        )]
    }

    private func uniffiCallbackInitOnSocketFdAvailableCallback() {
        uniffi_protun_fn_init_callback_vtable_onsocketfdavailablecallback(UniffiCallbackInterfaceOnSocketFdAvailableCallback.vtable)
    }

    // FfiConverter protocol for callback interfaces
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private enum FfiConverterCallbackInterfaceOnSocketFdAvailableCallback {
        fileprivate static let handleMap = UniffiHandleMap<OnSocketFdAvailableCallback>()
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    extension FfiConverterCallbackInterfaceOnSocketFdAvailableCallback: FfiConverter {
        typealias SwiftType = OnSocketFdAvailableCallback
        typealias FfiType = UInt64

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public static func lift(_ handle: UInt64) throws -> SwiftType {
            try handleMap.get(handle: handle)
        }

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
            let handle: UInt64 = try readInt(&buf)
            return try lift(handle)
        }

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public static func lower(_ v: SwiftType) -> UInt64 {
            handleMap.insert(obj: v)
        }

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
            writeInt(&buf, lower(v))
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterCallbackInterfaceOnSocketFdAvailableCallback_lift(_ handle: UInt64) throws -> OnSocketFdAvailableCallback {
        try FfiConverterCallbackInterfaceOnSocketFdAvailableCallback.lift(handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterCallbackInterfaceOnSocketFdAvailableCallback_lower(_ v: OnSocketFdAvailableCallback) -> UInt64 {
        FfiConverterCallbackInterfaceOnSocketFdAvailableCallback.lower(v)
    }

    public protocol StateChangedCallback: AnyObject, Sendable {
        func onStateChanged(state: State)
    }

    // Put the implementation in a struct so we don't pollute the top-level namespace
    private enum UniffiCallbackInterfaceStateChangedCallback {
        // Create the VTable using a series of closures.
        // Swift automatically converts these into C callback functions.
        //
        // This creates 1-element array, since this seems to be the only way to construct a const
        // pointer that we can pass to the Rust code.
        static let vtable: [UniffiVTableCallbackInterfaceStateChangedCallback] = [UniffiVTableCallbackInterfaceStateChangedCallback(
            onStateChanged: { (
                uniffiHandle: UInt64,
                state: RustBuffer,
                _: UnsafeMutableRawPointer,
                uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
            ) in
                let makeCall = {
                    () throws in
                    guard let uniffiObj = try? FfiConverterCallbackInterfaceStateChangedCallback.handleMap.get(handle: uniffiHandle) else {
                        throw UniffiInternalError.unexpectedStaleHandle
                    }
                    return try uniffiObj.onStateChanged(
                        state: FfiConverterTypeState_lift(state)
                    )
                }

                let writeReturn = { () }
                uniffiTraitInterfaceCall(
                    callStatus: uniffiCallStatus,
                    makeCall: makeCall,
                    writeReturn: writeReturn
                )
            },
            uniffiFree: { (uniffiHandle: UInt64) in
                let result = try? FfiConverterCallbackInterfaceStateChangedCallback.handleMap.remove(handle: uniffiHandle)
                if result == nil {
                    print("Uniffi callback interface StateChangedCallback: handle missing in uniffiFree")
                }
            }
        )]
    }

    private func uniffiCallbackInitStateChangedCallback() {
        uniffi_protun_fn_init_callback_vtable_statechangedcallback(UniffiCallbackInterfaceStateChangedCallback.vtable)
    }

    // FfiConverter protocol for callback interfaces
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private enum FfiConverterCallbackInterfaceStateChangedCallback {
        fileprivate static let handleMap = UniffiHandleMap<StateChangedCallback>()
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    extension FfiConverterCallbackInterfaceStateChangedCallback: FfiConverter {
        typealias SwiftType = StateChangedCallback
        typealias FfiType = UInt64

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public static func lift(_ handle: UInt64) throws -> SwiftType {
            try handleMap.get(handle: handle)
        }

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
            let handle: UInt64 = try readInt(&buf)
            return try lift(handle)
        }

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public static func lower(_ v: SwiftType) -> UInt64 {
            handleMap.insert(obj: v)
        }

        #if swift(>=5.8)
            @_documentation(visibility: private)
        #endif
        public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
            writeInt(&buf, lower(v))
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterCallbackInterfaceStateChangedCallback_lift(_ handle: UInt64) throws -> StateChangedCallback {
        try FfiConverterCallbackInterfaceStateChangedCallback.lift(handle)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterCallbackInterfaceStateChangedCallback_lower(_ v: StateChangedCallback) -> UInt64 {
        FfiConverterCallbackInterfaceStateChangedCallback.lower(v)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private struct FfiConverterOptionTypeDisconnectReason: FfiConverterRustBuffer {
        typealias SwiftType = DisconnectReason?

        public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
            guard let value else {
                writeInt(&buf, Int8(0))
                return
            }
            writeInt(&buf, Int8(1))
            FfiConverterTypeDisconnectReason.write(value, into: &buf)
        }

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
            switch try readInt(&buf) as Int8 {
            case 0: return nil
            case 1: return try FfiConverterTypeDisconnectReason.read(from: &buf)
            default: throw UniffiInternalError.unexpectedOptionalTag
            }
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private struct FfiConverterOptionCallbackInterfaceOnSocketFdAvailableCallback: FfiConverterRustBuffer {
        typealias SwiftType = OnSocketFdAvailableCallback?

        public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
            guard let value else {
                writeInt(&buf, Int8(0))
                return
            }
            writeInt(&buf, Int8(1))
            FfiConverterCallbackInterfaceOnSocketFdAvailableCallback.write(value, into: &buf)
        }

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
            switch try readInt(&buf) as Int8 {
            case 0: return nil
            case 1: return try FfiConverterCallbackInterfaceOnSocketFdAvailableCallback.read(from: &buf)
            default: throw UniffiInternalError.unexpectedOptionalTag
            }
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private struct FfiConverterSequenceUInt16: FfiConverterRustBuffer {
        typealias SwiftType = [UInt16]

        public static func write(_ value: [UInt16], into buf: inout [UInt8]) {
            let len = Int32(value.count)
            writeInt(&buf, len)
            for item in value {
                FfiConverterUInt16.write(item, into: &buf)
            }
        }

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt16] {
            let len: Int32 = try readInt(&buf)
            var seq = [UInt16]()
            seq.reserveCapacity(Int(len))
            for _ in 0 ..< len {
                try seq.append(FfiConverterUInt16.read(from: &buf))
            }
            return seq
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private struct FfiConverterSequenceTypePeerConnectionInfo: FfiConverterRustBuffer {
        typealias SwiftType = [PeerConnectionInfo]

        public static func write(_ value: [PeerConnectionInfo], into buf: inout [UInt8]) {
            let len = Int32(value.count)
            writeInt(&buf, len)
            for item in value {
                FfiConverterTypePeerConnectionInfo.write(item, into: &buf)
            }
        }

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PeerConnectionInfo] {
            let len: Int32 = try readInt(&buf)
            var seq = [PeerConnectionInfo]()
            seq.reserveCapacity(Int(len))
            for _ in 0 ..< len {
                try seq.append(FfiConverterTypePeerConnectionInfo.read(from: &buf))
            }
            return seq
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    private struct FfiConverterSequenceTypePeerInfo: FfiConverterRustBuffer {
        typealias SwiftType = [PeerInfo]

        public static func write(_ value: [PeerInfo], into buf: inout [UInt8]) {
            let len = Int32(value.count)
            writeInt(&buf, len)
            for item in value {
                FfiConverterTypePeerInfo.write(item, into: &buf)
            }
        }

        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [PeerInfo] {
            let len: Int32 = try readInt(&buf)
            var seq = [PeerInfo]()
            seq.reserveCapacity(Int(len))
            for _ in 0 ..< len {
                try seq.append(FfiConverterTypePeerInfo.read(from: &buf))
            }
            return seq
        }
    }

    /**
     * Typealias from the type name used in the UDL file to the builtin type.  This
     * is needed because the UDL type name is used in function/method signatures.
     */
    public typealias IpAddress = String

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypeIpAddress: FfiConverter {
        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IpAddress {
            try FfiConverterString.read(from: &buf)
        }

        public static func write(_ value: IpAddress, into buf: inout [UInt8]) {
            FfiConverterString.write(value, into: &buf)
        }

        public static func lift(_ value: RustBuffer) throws -> IpAddress {
            try FfiConverterString.lift(value)
        }

        public static func lower(_ value: IpAddress) -> RustBuffer {
            FfiConverterString.lower(value)
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeIpAddress_lift(_ value: RustBuffer) throws -> IpAddress {
        try FfiConverterTypeIpAddress.lift(value)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeIpAddress_lower(_ value: IpAddress) -> RustBuffer {
        FfiConverterTypeIpAddress.lower(value)
    }

    /**
     * Typealias from the type name used in the UDL file to the builtin type.  This
     * is needed because the UDL type name is used in function/method signatures.
     */
    public typealias WgClientPrivateKey = Data

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypeWgClientPrivateKey: FfiConverter {
        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WgClientPrivateKey {
            try FfiConverterData.read(from: &buf)
        }

        public static func write(_ value: WgClientPrivateKey, into buf: inout [UInt8]) {
            FfiConverterData.write(value, into: &buf)
        }

        public static func lift(_ value: RustBuffer) throws -> WgClientPrivateKey {
            try FfiConverterData.lift(value)
        }

        public static func lower(_ value: WgClientPrivateKey) -> RustBuffer {
            FfiConverterData.lower(value)
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeWgClientPrivateKey_lift(_ value: RustBuffer) throws -> WgClientPrivateKey {
        try FfiConverterTypeWgClientPrivateKey.lift(value)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeWgClientPrivateKey_lower(_ value: WgClientPrivateKey) -> RustBuffer {
        FfiConverterTypeWgClientPrivateKey.lower(value)
    }

    /**
     * Typealias from the type name used in the UDL file to the builtin type.  This
     * is needed because the UDL type name is used in function/method signatures.
     */
    public typealias WgPeerPublicKey = Data

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct FfiConverterTypeWgPeerPublicKey: FfiConverter {
        public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WgPeerPublicKey {
            try FfiConverterData.read(from: &buf)
        }

        public static func write(_ value: WgPeerPublicKey, into buf: inout [UInt8]) {
            FfiConverterData.write(value, into: &buf)
        }

        public static func lift(_ value: RustBuffer) throws -> WgPeerPublicKey {
            try FfiConverterData.lift(value)
        }

        public static func lower(_ value: WgPeerPublicKey) -> RustBuffer {
            FfiConverterData.lower(value)
        }
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeWgPeerPublicKey_lift(_ value: RustBuffer) throws -> WgPeerPublicKey {
        try FfiConverterTypeWgPeerPublicKey.lift(value)
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func FfiConverterTypeWgPeerPublicKey_lower(_ value: WgPeerPublicKey) -> RustBuffer {
        FfiConverterTypeWgPeerPublicKey.lower(value)
    }

    /**
     * Initialize the logger and backtrace. Should be called only once by the client.
     * [level] min log level to be logged.
     * [logger] callback for the client to receive log messages.
     */
    public func initLogger(level: LogLevel, logger: ClientLogger) { try! rustCall {
        uniffi_protun_fn_func_init_logger(
            FfiConverterTypeLogLevel_lower(level),
            FfiConverterCallbackInterfaceClientLogger_lower(logger), $0
        )
    }
    }

    private enum InitializationResult {
        case ok
        case contractVersionMismatch
        case apiChecksumMismatch
    }

    // Use a global variable to perform the versioning checks. Swift ensures that
    // the code inside is only computed once.
    private let initializationResult: InitializationResult = {
        // Get the bindings contract version from our ComponentInterface
        let bindings_contract_version = 29
        // Get the scaffolding contract version by calling the into the dylib
        let scaffolding_contract_version = ffi_protun_uniffi_contract_version()
        if bindings_contract_version != scaffolding_contract_version {
            return InitializationResult.contractVersionMismatch
        }
        if uniffi_protun_checksum_func_init_logger() != 145 {
            return InitializationResult.apiChecksumMismatch
        }
        if uniffi_protun_checksum_method_connection_disconnect() != 59943 {
            return InitializationResult.apiChecksumMismatch
        }
        if uniffi_protun_checksum_method_connection_on_set_network_available() != 42356 {
            return InitializationResult.apiChecksumMismatch
        }
        if uniffi_protun_checksum_method_connection_update_peers() != 15424 {
            return InitializationResult.apiChecksumMismatch
        }
        if uniffi_protun_checksum_method_connection_update_unix_tun() != 34209 {
            return InitializationResult.apiChecksumMismatch
        }
        if uniffi_protun_checksum_method_connection_update_wg_private_key() != 45720 {
            return InitializationResult.apiChecksumMismatch
        }
        if uniffi_protun_checksum_constructor_connection_unix_connect() != 63265 {
            return InitializationResult.apiChecksumMismatch
        }
        if uniffi_protun_checksum_method_clientlogger_log() != 37409 {
            return InitializationResult.apiChecksumMismatch
        }
        if uniffi_protun_checksum_method_onsocketfdavailablecallback_on_socket_fd_available() != 32002 {
            return InitializationResult.apiChecksumMismatch
        }
        if uniffi_protun_checksum_method_statechangedcallback_on_state_changed() != 30152 {
            return InitializationResult.apiChecksumMismatch
        }

        uniffiCallbackInitClientLogger()
        uniffiCallbackInitOnSocketFdAvailableCallback()
        uniffiCallbackInitStateChangedCallback()
        return InitializationResult.ok
    }()

    // Make the ensure init function public so that other modules which have external type references to
    // our types can call it.
    public func uniffiEnsureProtunInitialized() {
        switch initializationResult {
        case .ok:
            break
        case .contractVersionMismatch:
            fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
        case .apiChecksumMismatch:
            fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
        }
    }

    // swiftlint:enable all
#endif
